### ISSUE TITLE
Error when install with composer

### ISSUE THREAD

**Issue by husnixs** [bangadam/nik-parser-php#2]
Using version ^1.0 for bangadam/nik-parser-php
./composer.json has been updated
Running composer update bangadam/nik-parser-php
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires bangadam/nik-parser-php ^1.0 -> satisfiable by bangadam/nik-parser-php[1.0.0, 1.0.1].
    - bangadam/nik-parser-php[1.0.0, ..., 1.0.1] require illuminate/support 10.x-dev -> found illuminate/support[10.x-dev] but it does not match your minimum-stability.

You can also try re-running composer require with an explicit version constraint, e.g. "composer require bangadam/nik-parser-php:*" to figure out if any version is installable, or "composer require bangadam/nik-parser-php:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by sooluh** [comment]
Hello @yanuaraditia, I'm sorry for the mention. Your contribution on pull request #1 unfortunately caused a disruption to this package when used for non-Laravel applications. This is due to our current requirement for the [`illuminate/support`](https://github.com/bangadam/nik-parser-php/blob/master/composer.json#L20) package, which can overwhelm non-Laravel applications. I myself am unsure about how to make the PHP library support both PHP native and Laravel simultaneously. Is there a solution for this?
